#========================================================================================================================
# https://github.com/dianariyanto/dianwrt
# Description: Automatically Build Custom OpenWrt Firmware
# Function: Workflows for Build Custom OpenWrt Firmware
# Copyright (C) 2020 https://github.com/dianariyanto/dianwrt
#========================================================================================================================

name: HG680P

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  watch:
    types: started
    if: github.event.repository.owner.id == github.event.sender.id

env:
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        echo "FILE_DATE=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
    
    - name: Build
      id: build
      working-directory: /workdir
      run: |
        wget -c https://github.com/dianariyanto/lynx/releases/download/hg680p_DianWrt_21.02_2022.01.08.0456/DianWrt-21.02-k5.10.90-2022.01.08.0455.img.gz
        echo "::set-output name=status::success"
        
    - name: Check space usage
      if: (!cancelled())
      run: df -hT
      
    - name: Upload artifact to Actions
      uses: kittaakos/upload-artifact-as-is@master
      if: (!cancelled())
      with:
        path: /workdir/

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      if: steps.build.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: hg680p_DianWrt_21.02_${{ env.FILE_DATE }}
        files: /workdir/*
        body: |
          DianWrt based on OpenWrt 21.02 for HG680P using kernel 5.10.90
          
          ## Firmware information
          * Default IP: 192.168.1.1
          * Default username: root
          * Default password: passwd
          * Default WIFI name: NAUFAL.NET
          * Default WIFI password: podowingi
          * Install to EMMC: Login to OpenWrt → System → Amlogic Service → Install OpenWrt
